import { Button, Typography } from '@mui/material';
import Head from 'next/head';
import { setToaster, useAppDispatch } from '@/stores';
import { IconArrowLeft, IconSearch } from '@/components/icons';

export default function Home(): JSX.Element {
  const dispatch = useAppDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <Button
          variant="contained"
          onClick={() => {
            dispatch(
              setToaster({ message: 'test toaster', severety: 'info', key: 1 }),
            );
          }}
        >
          add toaster
        </Button>
        <Typography variant="h1">Rubik font</Typography>
        <IconArrowLeft />
        <IconSearch />
      </main>
    </>
  );
}
