import Head from 'next/head';
import { InferGetStaticPropsType } from 'next';
import {
  MainAppointment,
  MainInsurances,
  MainPopular,
  MainPromo,
  MainServices,
} from '@/components';
import { wrapper } from '@/stores';
import {
  getPopularSpecialtiesList,
  getRunningQueriesThunk,
  getServicesList,
} from '@/stores/api';

export const getStaticProps = wrapper.getStaticProps(store => async () => {
  const services = await store.dispatch(getServicesList.initiate());
  const specialties = await store.dispatch(
    getPopularSpecialtiesList.initiate(),
  );

  await Promise.all(store.dispatch(getRunningQueriesThunk()));

  return {
    props: {
      services: services.data,
      specialties: specialties.data,
    },
  };
});

export default function Home({
  services,
  specialties,
}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MainPromo />
      <MainAppointment />
      <MainPopular specialties={specialties} />
      <MainServices services={services} />
      <MainInsurances />
    </>
  );
}
